spring:
  datasource:
    url: jdbc:mysql://39.97.67.215:3306/zjcq?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml  #加载mapper配置文件 主配置文件可以省略，底层已经自动设置了
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印mybatis 日志
    map-underscore-to-camel-case: true #开启驼峰命名